name: flutter_line_sdk
description: A Flutter plugin for using the LINE SDKs with Dart in Flutter apps.
version: 2.3.1
homepage: https://developers.line.biz/
repository: https://github.com/line/flutter_line_sdk/

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.linecorp.flutter_line_sdk
        pluginClass: FlutterLineSdkPlugin
      ios:
        pluginClass: FlutterLineSdkPlugin
